name: CI Linux/macOS

on:
  push:
    branches:
      - 'testing_*'
  pull_request:
    branches:
      - 'testing_*'
      - master
jobs:
  ubuntu-build-qt5:
    name: Ubuntu CI QT5
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt-get -y install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libsqlite3-dev libhamlib++-dev libqt5charts5-dev qttools5-dev-tools libqt5keychain1 qt5keychain-dev qtwebengine5-dev build-essential libqt5serialport5-dev pkg-config libqt5websockets5-dev
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: configure
      run: qmake QLog.pro
    - name: make
      run: make -j2

  ubuntu-build-qt6:
    name: Ubuntu CI QT6
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt-get -y install libhamlib-dev build-essential pkg-config qt6-base-dev qtkeychain-qt6-dev qt6-webengine-dev libqt6charts6-dev libqt6serialport6-dev libqt6webenginecore6-bin libqt6svg6-dev libgl-dev libqt6websockets6-dev
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: configure
      run: qmake6 QLog.pro
    - name: make
      run: make -j2

  macos-build:
     name: MacOS CI
     strategy:
       matrix:
         os: [macos-15]

     runs-on: ${{ matrix.os }}

     steps:
     - name: Install dependencies
       run: |
         unset HOMEBREW_NO_INSTALL_FROM_API
         brew update
         brew upgrade || true
         brew install qt6
         brew link qt6 --force
         brew install hamlib
         brew link hamlib --force
         brew install qtkeychain
         brew install dbus-glib
         brew install brotli
         brew install icu4c
         brew install pkg-config

     - name: Checkout code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
         submodules: recursive
     - name: Get version from tag
       run : |
         TAGVERSION=$(git describe --tags)
         echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV
     - name: Configure and compile
       run: |
         mkdir build
         cd build
         qmake6 -config release ..
         make -j4
